### ISSUE TITLE
Failed to load plugin music-code-blocks

### ISSUE THREAD

**Issue by libenling** [abcjs-music/obsidian-plugin-abcjs#22]
Error "Failed to load plugin music-code-blocks" shows, when enabling this plugin.
 
![uTools_1666236814545](https://user-images.githubusercontent.com/92899170/196855590-11ba18f7-4ea7-4c3b-95ae-9c9e01a4d69e.png)

My Obsidian version is: 1.0.0
OS is Windows10

**Comment by TilBlechschmidt** [comment]
Hey @libenling, could you please open up the developer console (from the menubar) and see if there are any errors in there? That would greatly help in analyzing the issue as the plugin runs for me on version 1.0.0

**Comment by alensiljak** [comment]
Hi, @libenling, could you please confirm if this is still the case?

**Comment by alensiljak** [comment]
I can't reproduce on Windows nor Android (so far). Please reopen if the issue persists.

**Comment by libenling** [comment]
Thanks for helping me, I tried again to download the plugin from https://github.com/abcjs-music/obsidian-plugin-abcjs/releases/tag/1.2.0, and it work properly this time.
And I found the reason was the absence of the file "main.js" when I downloaded the plugin from Obsidian->settings->Community plugins.
Sorry to bother and thanks again.

**Comment by alensiljak** [comment]
Right, no worries. I'm also new to the deployment process and find it a bit sharp. A push to the master branch will make everyone use the manifest with the new version, which expects the release with the output files to exist in order to download. I find that a bit counterintuitive but it's just something that requires getting used to and creating the Release **before** pushing the changes to GitHub. :D
