### ISSUE TITLE
Can we simply use ```abc``` as an alias for language specific ?

### ISSUE THREAD

**Issue by ivaquero** [abcjs-music/obsidian-plugin-abcjs#25]
I think `abc` is more popular to be used as language specific than `music-abc` (e.g. VSCode, Sublime). Using `abc` can be helpful for users to switch over different applications.

So, could you please make `abc` an alias while keeping `music-abc`.

**Comment by alensiljak** [comment]
I agree that the choice of the syntax specifier could have been different. However, changing it now would be a breaking change that would affect all the existing uses. Meaning all the users would have to rewrite their existing code snippets just so that they would work again.

It might be useful to research if it is possible to register two syntax specifiers. In which case, `abc` (but `abc` is also too generic - it does not state that it is the ABC Music Notation spec) could slowly replace `music-abc` over time.

**Comment by alensiljak** [comment]
Based on the very first line
```
this.registerMarkdownCodeBlockProcessor('music-abc', async
```
it appears that it should be doable. I'd certainly like to write my music code as `abc` right from the start.

**Comment by alensiljak** [comment]
OK, that was pretty painless to implement!
Ref v1.2

**Comment by ivaquero** [comment]
Thank you!
